packages:
    - packages/*
    - packages/*/samples/*
    - packages/*/test-e2e/__testfiles__/*

ignoredBuiltDependencies:
    - ejs
    - esbuild
    - unrs-resolver

onlyBuiltDependencies:
    - node-expat
