
jobs:
  test:
    parameters:
        docker_image:
          type: string
          default: cimg/node:current
    docker:
      - image: << parameters.docker_image >>
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            rm -rf node_modules package-lock.json
            npm install
      - run:
          name: Running all unit tests
          command: |
            node -v
            npm -v
            npm run test

