version: 2.1
jobs:
  test12:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ls -la
            rm -rf node_modules package-lock.json
            npm install
            NODE=$(dirname $(dirname $(which node)))
            sed "s@XXXX@$NODE@" build.properties.travis > build.properties
      - run:
          name: Running all unit tests
          command: |
            node -v
            npm -v
            npm run test
  test10:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ls -la
            rm -rf node_modules package-lock.json
            npm install
            NODE=$(dirname $(dirname $(which node)))
            sed "s@XXXX@$NODE@" build.properties.travis > build.properties
      - run:
          name: Running all unit tests
          command: |
            node -v
            npm -v
            npm run test
  testCurrent:
    docker:
      - image: circleci/node:current-browsers
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            ls -la
            rm -rf node_modules package-lock.json
            npm install
            NODE=$(dirname $(dirname $(which node)))
            sed "s@XXXX@$NODE@" build.properties.travis > build.properties
      - run:
          name: Running all unit tests
          command: |
            node -v
            npm -v
            npm run test

workflows:
  version: 2
  test-all-node-versions:
    jobs:
      - test12
      - test10
      - testCurrent
