version: 2.1
orbs:
    node: circleci/node@6.3.0
    browser-tools: circleci/browser-tools@1.4.8
workflows:
    test:
        jobs:
            - test
jobs:
    test:
        executor:
            name: node/default
            tag: 22.11-browsers
        environment:
            TURBO_UI: "false"
            CHROME_BIN: /usr/bin/google-chrome
        steps:
            - browser-tools/install-browser-tools
            - checkout
            - node/install-packages:
                  pkg-manager: pnpm
            - run:
                  command: pnpm build
            - run:
                  command: pnpm test
