version: 2.1
orbs:
    node: circleci/node@6.3.0
workflows:
    test:
        jobs:
            - test
jobs:
    test:
        executor:
            name: node/default
            tag: lts
        steps:
            - checkout
            - node/install-packages:
                  pkg-manager: pnpm
            - run:
                  command: pnpm build
                  environment:
                      TURBO_UI: "false"
            - run:
                  command: pnpm test
                  environment:
                      TURBO_UI: "false"
