version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:12-browsers
    steps:
      - run:
          name: Setup
          command: |
            ls -la
            rm -rf node_modules package-lock.json
            npm install
            NODE=$(dirname $(dirname $(which node)))
            sed "s@XXXX@$NODE@" build.properties.travis > build.properties
      - run:
          name: Running all unit tests
          command: |
            node -v
            npm -v
            npm run test
