#!/usr/bin/env node

/*
 * generate.ts - tool to generate glyph/normalization information from
 * the Unicode UCD data files
 *
 * Copyright © 2013-2018, 2020-2022, 2024, 2026 JEDLSoft
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

/*
 * Adapted from ilib/tools/cldr/gennorm.js. GlyphString only needs the
 * combining-class table (ccc) and the canonical composition map (nfc),
 * both of which are static (not locale-sensitive), so they are written
 * as TypeScript modules under src/.
 */

import fs from "fs";
import path from "path";
import dedent from "dedent";
import stringify from "json-stable-stringify";

import { Utils } from "ilib-data-utils";

const moduleRoot = path.resolve(__dirname, "..");
const srcDir = path.join(moduleRoot, "src");
const ucdDir = path.join(moduleRoot, "node_modules", "ucd-full");

interface UcdRangeEntry {
    property: string;
    range: string[];
}

interface UcdUnicodeDataEntry {
    codepoint: string;
    characterDecompositionMapping?: string;
    canonicalCombiningClass: number | string;
}

interface DerivedNormalizationPropsFile {
    DerivedNormalizationProps: UcdRangeEntry[];
}

interface UnicodeDataFile {
    UnicodeData: UcdUnicodeDataEntry[];
}

function usage(): never {
    console.log(
        "Usage: generate [-h]\n" +
            "Generate the glyph normalization data as TypeScript modules.\n\n" +
            "-h or --help\n" +
            "  this help\n"
    );
    process.exit(1);
}

process.argv.forEach((val) => {
    if (val === "-h" || val === "--help") {
        usage();
    }
});

console.log(
    "generate - generate glyph normalization data.\n" +
        "Copyright (c) 2013-2018, 2020-2022, 2024, 2026 JEDLSoft"
);

function loadJson<T>(filePath: string): T {
    return JSON.parse(fs.readFileSync(filePath, "utf-8")) as T;
}

/**
 * Write a generated TypeScript data module under src/.
 */
function writeTs(
    name: "ccc" | "nfc",
    typeName: string,
    typeDoc: string,
    valueType: string,
    data: Record<string, number> | Record<string, string>
): void {
    const year = new Date().getFullYear();
    const dataLiteral = stringify(data, { space: 4 }) ?? "{}";

    // Write the template indented with this function body; `dedent`
    // strips the shared leading whitespace so the emitted file is
    // left-aligned. The data literal is concatenated outside the
    // template so its own indentation is not rewritten.
    const prefix = dedent`
        /*
         * ${name}.ts - Unicode normalization data
         *
         * Copyright © ${year} JEDLSoft
         *
         * Licensed under the Apache License, Version 2.0 (the "License");
         * you may not use this file except in compliance with the License.
         * You may obtain a copy of the License at
         *
         *     http://www.apache.org/licenses/LICENSE-2.0
         *
         * Unless required by applicable law or agreed to in writing, software
         * distributed under the License is distributed on an "AS IS" BASIS,
         * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
         *
         * See the License for the specific language governing permissions and
         * limitations under the License.
         *
         * This file is auto-generated from the ucd-full package.
         * Do not edit this file directly. Run \`pnpm build:data\` to regenerate.
         */

        /** ${typeDoc} */
        export type ${typeName} = Readonly<Record<string, ${valueType}>>;

        export const ${name}: ${typeName} =
    `;
    // Space after "=" is added here — dedent trims trailing whitespace
    // from the template, so it cannot live inside the tag.
    const contents = `${prefix} ${dataLiteral};\n`;

    const fileName = path.join(srcDir, `${name}.ts`);
    console.log(`Writing file ${fileName} ...`);
    fs.writeFileSync(fileName, contents, "utf-8");
}

const compositionExclusions: number[][] = [];
const canonicalMappings: Record<string, string> = {};
const canonicalComp: Record<string, string> = {};
const combiningMappings: Record<string, number> = {};

const ef = loadJson<DerivedNormalizationPropsFile>(
    path.join(ucdDir, "DerivedNormalizationProps.json")
);
for (const entry of ef.DerivedNormalizationProps) {
    if (entry.property === "Full_Composition_Exclusion") {
        compositionExclusions.push(entry.range.map((element) => parseInt(element, 16)));
    }
}

const ud = loadJson<UnicodeDataFile>(path.join(ucdDir, "UnicodeData.json"));

for (const entry of ud.UnicodeData) {
    const c = Utils.hexStringUTF16String(entry.codepoint);

    // Decomposition type is given in <angle brackets> at the start of the
    // mapping. No angle brackets means a canonical mapping.
    if (entry.characterDecompositionMapping) {
        let decomposition = entry.characterDecompositionMapping;
        if (decomposition.length && decomposition[0] === "<") {
            // compatibility mapping — not needed for GlyphString / NFC compose
        } else {
            decomposition = Utils.hexStringUTF16String(decomposition);
            canonicalMappings[c] = decomposition;
            if (!Utils.isMember(compositionExclusions, Utils.UTF16ToCodePoint(c))) {
                canonicalComp[decomposition] = c;
            }
        }
    }

    const ccc = Number(entry.canonicalCombiningClass);
    if (ccc > 0) {
        combiningMappings[c] = ccc;
    }
}

if (!fs.existsSync(srcDir)) {
    fs.mkdirSync(srcDir, { recursive: true });
}

writeTs(
    "ccc",
    "CombiningClassTable",
    "Map from a character to its canonical combining class (non-zero only).",
    "number",
    combiningMappings
);
writeTs(
    "nfc",
    "CompositionTable",
    "Map from a canonical decomposition sequence to its precomposed character.",
    "string",
    canonicalComp
);

console.log(
    `Done. Wrote ${Object.keys(combiningMappings).length} ccc entries and ${Object.keys(canonicalComp).length} nfc entries.`
);
