/*
 * samples.e2e.test.js - E2E tests for ilib-loctool-android-layout samples
 *
 * Copyright © 2025, Box, Inc.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 *
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

const path = require("path");
const fs = require("fs");
const { expectFileToMatchSnapshot, LoctoolRunner } = require("ilib-internal");

describe("samples", () => {
    describe("android", () => {
        const projectPath = path.resolve(__dirname, "..", "samples", "android");
        const xliffPath = path.resolve(projectPath, "sample-extracted.xliff");

        beforeAll(async () => {
            const loctool = new LoctoolRunner(projectPath);
            await loctool.run("localize");
        });

        afterAll(() => {
            // Clean up all files generated by loctool localize
            const filesToClean = [
                xliffPath, // sample-extracted.xliff
                path.resolve(projectPath, "sample-new-ko-KR.xliff"),
                path.resolve(projectPath, "sample-new-ru-RU.xliff"),
                path.resolve(projectPath, "res/values/strings-auto.xml")
            ];

            filesToClean.forEach(file => {
                if (fs.existsSync(file)) {
                    fs.unlinkSync(file);
                }
            });

            // Clean up generated directories
            const dirsToClean = [
                path.resolve(projectPath, "res/values-ko"),
                path.resolve(projectPath, "res/values-ru")
            ];

            dirsToClean.forEach(dir => {
                if (fs.existsSync(dir)) {
                    fs.rmSync(dir, { recursive: true, force: true });
                }
            });
        });

        it("should produce an extracted XLIFF file", () => {
            expectFileToMatchSnapshot(xliffPath);
        });
    });
});
