version: 2.1
jobs:
  test-loctool:
    parameters:
        docker_image:
          type: string
          default: cimg/node:current-browsers
    docker:
      - image: << parameters.docker_image >>
    steps:
      - checkout
      - run:
          name: Setup
          command: |
            cd packages/loctool
            ls -la
            rm -rf node_modules package-lock.json
            npm install
            NODE=$(dirname $(dirname $(which node)))
            sed "s@XXXX@$NODE@" build.properties.travis > build.properties
      - run:
          name: Running all unit tests
          command: |
            cd packages/loctool
            node -v
            npm -v
            npm run test --detectOpenHandles

workflows:
  version: 2
  test-loctool-with-all-node-versions:
    jobs:
      - test-loctool:
          docker_image: circleci/node:10-browsers
      - test-loctool:
          docker_image: circleci/node:12-browsers
      - test-loctool:
          docker_image: cimg/node:14.21
      - test-loctool:
          docker_image: cimg/node:16.19
      - test-loctool:
          docker_image: cimg/node:18.9
      - test-loctool:
          docker_image: cimg/node:20.9
      - test-loctool
