name: Test Affected

on: pull_request

jobs:
    test-affected:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [20]
        env:
            TURBO_UI: "false"
        steps:
            - uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v4
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: pnpm
            - name: Install Chrome
              uses: browser-actions/setup-chrome@v1
            - name: Install dependencies
              run: pnpm install --frozen-lockfile
            - name: Run affected tests
              run: pnpm test:ci:affected
